[project]
authors = ["Alex Nagorny <alex@swaygang.com>"]
entry = "main.sw"
license = "Apache-2.0"
name = "market"

[dependencies]
oracle_abi = { path = "../../abi/oracle_abi" }
# signed_integers = { git = "https://github.com/FuelLabs/sway-libs" }